---
- name: provisioning build environment
  hosts: build
  become: yes
  tasks:
    - name: Ensure the packages is present
      apt: name={{item}} state=present
      with_items:
        - maven
        - tomcat9
        - git
      state: present
    - name: Ensure demo project is downloaded
      git:
        repo: https://github.com/Ullubiy/Ansible.git
        dest: /opt
        clone: yes
    - name: Ensure the war is build
      command: mvn --batch-mode --quiet install
      args:
        chdir: /opt/Ansible/target/webapp.war
    - name: Ensure the war copy from build to master
      synchronize:
        mode: pull
        src: /opt/Ansible/target/webapp.war
        dest: /opt/
- name: provisioning prod environment
  hosts: prod
  become: yes
  tasks:
    - name: Ensure the java is present
      apt:
        name: default-jdk
        state: present
    - name: Ensure the tomcat9 is present
      apt:
        name: tomcat9
        state: present
    - name: Ensure the tomcat9 is present
      apt:
        name: tomcat9
        state: present
    - name: Ensure the war copy from build to prod
      synchronize:
        mode: push
        src: /opt/Ansible/target/webapp.war
        dest: /opt/lib/tomcat9/webapps/
